name: OpenSSF Scorecard

on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly

jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run OpenSSF Scorecard analysis
        uses: ossf/scorecard-action@v2
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload Scorecard results to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
